### ISSUE TITLE
Feature for online networks like Vatsim....

### ISSUE THREAD

**Issue by kwieser76** [TheChed/PSXMSFS#2]
As A PSX User, I want the following data to be synced to MSFS so that my data can be used for online networks.
- Traffic data
- TCAS status
- COM 1 / 2

**Comment by TheChed** [comment]
Hi,
I am working on Traffic and hopefully will be done in the next days or so.
COM 1/2 and XPDR should be fast too to implement.

**Comment by TheChed** [comment]
New version has the above features
