### ISSUE TITLE
Pushback

### ISSUE THREAD

**Issue by kwieser76** [TheChed/PSXMSFS#3]
As a PSX User using MSFS for online flights like on Vatsim I want that I can use a pushback tool in MSFS for both programs ( PSX and MSFS) so that on the online traffic I'm on the correct position as the internal PSX pushback tool is too inaccurate

**Comment by TheChed** [comment]
How would you use such a pushback tool ?

**Comment by kwieser76** [comment]
Right now the tool sync the position from PSX to MSFS. For the pushback it would be great if the sync will be done from MSFS to PSX and after the pushback again sync PSX- MSFS

**Comment by VolleyballCALVA** [comment]
It would be great if this can be done. Thank you very much for your efforts.

**Comment by TheChed** [comment]
working on it. But the logic behind the scenes is quite tough to revert

**Comment by TheChed** [comment]
Should be ok with the latest release now
