### ISSUE TITLE
Start location source

### ISSUE THREAD

**Issue by kwieser76** [TheChed/PSXMSFS#4]
As a PSX User what use PSX for online Flight like on Vatsim I want have the possibility to selected the start location from MSFS location and not from PSY as sometimes the PSX are the same as in MSFS what bring us to a problem that the start position is for the controller not on the correct position.

**Comment by TheChed** [comment]
But then, MSFS would be the master and PSX the slave.
At one point PSX has to be the leader in updating the position

**Comment by kwieser76** [comment]
yes correct ... 

possible option

1. Start with 
a) MSFS master
b) PSX slave 
after that, it will shall be switched.
( that option is then maybe also required for the pushback if you use the MSFS pushback toll as master)

2. start with (as today)
a) PSX master
b) MSFS slave

**Comment by TheChed** [comment]
on your first option, the big problem is to know when we can switch back. There is no easy way of doing so.
But let me see if I find a solution

**Comment by TheChed** [comment]
Should be Ok now with the latest release
